### ISSUE TITLE
IP has encountered a critical error!

### ISSUE THREAD

**Issue by festation2003** [Efnilite/Walk-in-the-Park#102]
Folders removed so new versions could completely regenerate and still having the same issue

[10:51:25 ERROR]: [IP] ##
[10:51:25 ERROR]: [IP] ## IP has encountered a critical error!
[10:51:25 ERROR]: [IP] ## Error while trying to read schematic plugins\IP\schematics\parkour-0442a82a
[10:51:25 ERROR]: [IP] ##
[10:51:25 ERROR]: [IP] ## Stack trace:
[10:51:25 ERROR]: [IP] ## java.io.StreamCorruptedException: invalid stream header: EFBFBDEF
[10:51:25 ERROR]: [IP] ##       java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:958)
[10:51:25 ERROR]: [IP] ##       java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:392)
[10:51:25 ERROR]: [IP] ##       IP-5.1.0.jar//dev.efnilite.ip.schematic.io.SchematicReader.read(SchematicReader.java:27)
[10:51:25 ERROR]: [IP] ##       IP-5.1.0.jar//dev.efnilite.ip.schematic.Schematic.lambda$new$0(Schematic.java:56)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:51:25 ERROR]: [IP] ##       java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:51:25 ERROR]: [IP] ##
[10:51:25 ERROR]: [IP] ## This is probably not your fault.
[10:51:25 ERROR]: [IP] ## Contact the developer to fix it.
[10:51:25 ERROR]: [IP] ## Be sure to send the entire error while reporting.
[10:51:25 ERROR]: [IP] ##
[10:51:25 ERROR]: [IP] ## Version information:
[10:51:25 ERROR]: [IP] ##       Plugin Version: 5.1.0
[10:51:25 ERROR]: [IP] ##       vilib Version: 1.2.0
[10:51:25 ERROR]: [IP] ##       Minecraft: V1.20
[10:51:25 ERROR]: [IP] ##
[10:51:25 WARN]: [IP] Plugin IP v5.1.0 generated an exception while executing task 3550
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsValue(Object)" because "this.vectorBlockMap" is null
        at dev.efnilite.ip.schematic.Schematic.isSupported(Schematic.java:97) ~[IP-5.1.0.jar:?]
        at dev.efnilite.ip.schematic.Schematics.lambda$init$1(Schematics.java:50) ~[IP-5.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-17]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.jar:git-Paper-17]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/2ff7f708e6bf54ae9ebb61c67405716480c46291. Thanks for reporting.
