### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by WongIong** [Efnilite/Walk-in-the-Park#104]
**Describe the bug**
Error that will crash servers

**To Reproduce**
Start your server and wait

**Screenshots**

**Errors**
`[16:15:38] [Craft Scheduler Thread - 20091 - IP/WARN]: [IP] Plugin IP v5.1.0 generated an exception while executing task 17592389
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at dev.efnilite.ip.player.ParkourSpectator.lambda$new$1(ParkourSpectator.java:58) ~[IP-5.1.0.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Versions**
- Plugin version 5.1.0
- Spigot/Paper version Paper 1.17.1

**Additional context**

**Comment by WongIong** [comment]
`[17:33:51] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:33:51] [Paper Watchdog Thread/ERROR]: 	PID: 25 | Suspended: false | Native: false | State: RUNNABLE
[17:33:51] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:33:51] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ChunkHolder.updateFutures(ChunkHolder.java:699)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.DistanceManager.runAllUpdates(DistanceManager.java:215)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:847)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.DistanceManager.addPriorityTicket(DistanceManager.java:418)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.DistanceManager.markUrgent(DistanceManager.java:345)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:763)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:667)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.world.level.Level.getChunk(Level.java:534)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.world.level.Level.getBlockState(Level.java:873)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getType(CraftBlock.java:215)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		IP-5.1.0.jar//dev.efnilite.ip.generator.ParkourGenerator.tick(ParkourGenerator.java:416)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		IP-5.1.0.jar//dev.efnilite.ip.generator.ParkourGenerator$$Lambda$10426/0x00000008028c5d40.run(Unknown Source)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		app//net.minecraft.server.MinecraftServer$$Lambda$3667/0x00000008013dae98.run(Unknown Source)
[17:33:53] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.7/java.lang.Thread.run(Thread.java:833)`

**Comment by Efnilite** [comment]
This'll be fixed in the next version. Thanks for reporting.
