### ISSUE TITLE
Error while trying to reconnect to MySQL

### ISSUE THREAD

**Issue by FatildaIV** [Efnilite/Walk-in-the-Park#107]
**Describe the bug**
IP is unable to connect to the database server.

**To Reproduce**
At server launch, plugin gets disabled automatically.

**Errors**
```
Enabling IP v5.1.0
Created config file schematics/schematics.yml
Registered style red
Registered style blue
Registered style light blue
Registered style green
Registered style lime
Registered style cyan
Registered style purple
Registered style yellow
Registered style gray
Registered style end
Registered style nether
Registered style quartz
Registered style ocean
Registered style redstone
Registered style overworld
Registered style ores
Registered style wood
Registered style rainbow
Registered style glow
Loaded all config files
Connecting to MySQL
##
## IP has encountered a critical error!
## Could not connect to MySQL
##
## Stack trace:
## java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 5 times. Giving up.
##	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
##	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
##	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
##	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
##	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
##	com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:895)
##	com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820)
##	com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
##	com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
##	com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
##	java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
##	java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
##	IP-v5.1.0.jar//dev.efnilite.ip.storage.StorageSQL.connect(StorageSQL.java:180)
##	IP-v5.1.0.jar//dev.efnilite.ip.storage.StorageSQL.<init>(StorageSQL.java:26)
##	IP-v5.1.0.jar//dev.efnilite.ip.IP.enable(IP.java:97)
##	vilib-v1.2.0.jar//dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59)
##	org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
##	io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
##	io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
##	org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
##	org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653)
##	org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564)
##	net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
##	net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
##	net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
##	net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
##	net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
##	java.base/java.lang.Thread.run(Thread.java:833)
##
## This is probably not your fault, but you may be able to fix it.
## You should try: check your SQL settings in the config
## Contact the developer if this doesn't work.
## Be sure to send the entire error while reporting.
##
## Version information:
##	Plugin Version: 5.1.0
##	vilib Version: 1.2.0
##	Minecraft: V1.20
##
Disabling IP v5.1.0
Error occurred (in the plugin loader) while disabling IP v5.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.efnilite.ip.mode.DefaultMode.getLeaderboard()" because "dev.efnilite.ip.mode.Modes.DEFAULT" is null
	at dev.efnilite.ip.IP.disable(IP.java:156) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.vilib.ViPlugin.onDisable(ViPlugin.java:64) ~[vilib-v1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.efnilite.ip.storage.StorageSQL.connect(StorageSQL.java:210) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.storage.StorageSQL.<init>(StorageSQL.java:26) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.IP.enable(IP.java:97) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[vilib-v1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
##
## IP has encountered a critical error!
## Error while trying to reconnect to MySQL
##
## Stack trace:
## java.lang.NullPointerException: Cannot invoke "java.sql.Connection.isValid(int)" because "this.connection" is null
##	IP-v5.1.0.jar//dev.efnilite.ip.storage.StorageSQL.validateConnection(StorageSQL.java:216)
##	IP-v5.1.0.jar//dev.efnilite.ip.storage.StorageSQL.sendUpdate(StorageSQL.java:238)
##	IP-v5.1.0.jar//dev.efnilite.ip.storage.StorageSQL.init(StorageSQL.java:31)
##	IP-v5.1.0.jar//dev.efnilite.ip.leaderboard.Leaderboard.<init>(Leaderboard.java:36)
##	IP-v5.1.0.jar//dev.efnilite.ip.mode.DefaultMode.<init>(DefaultMode.java:22)
##	IP-v5.1.0.jar//dev.efnilite.ip.IP.enable(IP.java:101)
##	vilib-v1.2.0.jar//dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59)
##	org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
##	io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
##	io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
##	org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
##	org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653)
##	org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564)
##	net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
##	net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440)
##	net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
##	net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
##	net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
##	java.base/java.lang.Thread.run(Thread.java:833)
##
## This is probably not your fault.
## Contact the developer to fix it.
## Be sure to send the entire error while reporting.
##
## Version information:
##	Plugin Version: 5.1.0
##	vilib Version: 1.2.0
##	Minecraft: V1.20
##
Error occurred while enabling IP v5.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.connection" is null
	at dev.efnilite.ip.storage.StorageSQL.sendUpdate(StorageSQL.java:240) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.storage.StorageSQL.init(StorageSQL.java:31) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.leaderboard.Leaderboard.<init>(Leaderboard.java:36) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.mode.DefaultMode.<init>(DefaultMode.java:22) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.ip.IP.enable(IP.java:101) ~[IP-v5.1.0.jar:?]
	at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[vilib-v1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Versions**
- Plugin version: Both 5.1.0 and https://github.com/Efnilite/Walk-in-the-Park/commit/1e09073ebe679a0c81fb5fc6dad65e4a56ec9be5 tested.
- Spigot/Paper version: git-Purpur-2023 (MC: 1.20.1)
- MariaDB 11.0.2-2

**Additional context**
Recently I've encountered some problems with Java applications using MySQL Connector/J to connect to the MariaDB 11 server. MySQL Connector/J 8.0.33 (latest) isn't compatible with MariaDB servers 11 or newer, using latest version of MariaDB Connector/J is recommended by MariaDB Foundation. I'll investigate the issue more and comment with results.

**Comment by FatildaIV** [comment]
MariaDB service log:
`[Warning] Aborted connection 32959 to db: 'xxx' user: 'yyy' host: 'localhost' (Got an error reading communication packets)`
