### ISSUE TITLE
Scoreboard is not showing the score & time etc

### ISSUE THREAD

**Issue by adalmo** [Efnilite/Walk-in-the-Park#112]
**Describe the bug**
Scoreboard is not showing the score & time etc
**To Reproduce**
apply the plugin and launch the server
[15:26:59 WARN]: [IP] Task #1781 for IP v5.1.2 generated an exception
java.lang.RuntimeException: Unable to update scoreboard lines
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:350) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.player.ParkourUser.updateScoreboard(ParkourUser.java:276) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.generator.ParkourGenerator.lambda$tick$5(ParkourGenerator.java:402) ~[IP-5.1.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.efnilite.ip.generator.ParkourGenerator.tick(ParkourGenerator.java:400) ~[IP-5.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String
        at jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:137) ~[?:?]
        at jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:141) ~[?:?]
        at jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:103) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:820) ~[?:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.setField(FastBoardBase.java:559) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.sendScorePacket(FastBoardBase.java:475) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:338) ~[IP-5.1.2.jar:?]
        ... 12 more
**Screenshots**
![image](https://github.com/Efnilite/Walk-in-the-Park/assets/88581750/68ed5244-05d7-4fac-9cfb-e4f990c2c0b9)
![image](https://github.com/Efnilite/Walk-in-the-Park/assets/88581750/0150e7e3-d166-4f23-a006-ff62488f1952)

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.
[15:26:59 WARN]: [IP] Task #1781 for IP v5.1.2 generated an exception
java.lang.RuntimeException: Unable to update scoreboard lines
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:350) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.player.ParkourUser.updateScoreboard(ParkourUser.java:276) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.generator.ParkourGenerator.lambda$tick$5(ParkourGenerator.java:402) ~[IP-5.1.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.efnilite.ip.generator.ParkourGenerator.tick(ParkourGenerator.java:400) ~[IP-5.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String
        at jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:137) ~[?:?]
        at jdk.internal.reflect.FieldAccessorImpl.throwFinalFieldIllegalAccessException(FieldAccessorImpl.java:141) ~[?:?]
        at jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:103) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:820) ~[?:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.setField(FastBoardBase.java:559) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.sendScorePacket(FastBoardBase.java:475) ~[IP-5.1.2.jar:?]
        at dev.efnilite.ip.vilib.fastboard.FastBoardBase.updateLines(FastBoardBase.java:338) ~[IP-5.1.2.jar:?]
        ... 12 more
**Versions**
- Plugin version 5.1.2 hotfix
- Spigot/Paper version Current: git-Purpur-2110 (MC: 1.20.4)*
* You are running the latest version

**Additional context**

**Comment by Efnilite** [comment]
Seems the scoreboard library I use doesn't support 1.20.4 yet, although a 1.20.3 version has been released. I will test to see whether that one fixes it for 1.20.4 as well.

**Comment by adalmo** [comment]
sure

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/029c462d29a7b41bf4faeb8c19cdd4e1a57f3757. You should see this in the next release. Thanks for reporting!
