### ISSUE TITLE
Can't get into the parkour world

### ISSUE THREAD

**Issue by YinHuansleep** [Efnilite/Walk-in-the-Park#128]
**Describe the bug**
Execution error：/ip join

**Errors**
[Minecraft]: Could not pass event InventoryClickEvent to IP v5.2.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-1.18.2-1.0.12-fded76e.jar%2370!/:arclight-1.18.2-1.0.12-fded76e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-1.18.2-1.0.12-fded76e.jar%2370!/:arclight-1.18.2-1.0.12-fded76e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-1.18.2-1.0.12-fded76e.jar%2370!/:arclight-1.18.2-1.0.12-fded76e]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3014) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.network.protocol.PacketUtils.md6628c5$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23210!/:? ]
at java.lang.Thread.run(Thread.java:842) [?:? ]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionEffectType.getId()" because "type" is null
at org.bukkit.craftbukkit.v1_18_R2.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:389) ~[arclight-1.18.2-1.0.12-fded76e.jar%2370!/:arclight-1.18.2-1.0.12-fded76e]
at dev.efnilite.ip.player.ParkourPlayer.<init>(ParkourPlayer.java:91) ~[?:? ]
at dev.efnilite.ip.player.ParkourUser.register(ParkourUser.java:65) ~[?:? ]
at dev.efnilite.ip.session.Session.create(Session.java:81) ~[?:? ]
at dev.efnilite.ip.mode.DefaultMode.create(DefaultMode.java:53) ~[?:? ]
at dev.efnilite.ip.menu.play.SingleMenu.open(SingleMenu.java:55) ~[?:? ]
at dev.efnilite.ip.menu.play.PlayMenu.lambda$new$0(PlayMenu.java:18) ~[?:? ]
at dev.efnilite.ip.lib.vilib.inventory.item.MenuItem.handleClick(MenuItem.java:51) ~[?:? ]
at dev.efnilite.ip.lib.vilib.inventory.Menu.click(Menu.java:306) ~[?:? ]
...  20 more

**Versions**
IP-5.2.5

**Comment by YinHuansleep** [comment]
Rollback A version to work properly (5.2.4)

**Comment by Efnilite** [comment]
Try redownloading 5.2.5 from GitHub.
