### ISSUE TITLE
NullPointerException: null - ParkourUser.leaderboard

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#13]
```
[10:08:13] [Server thread/ERROR]: Could not pass event InventoryClickEvent to WITP v2.0
[10:08:13] [Server thread/ERROR]: Suspected Plugins: 
[10:08:13] [Server thread/ERROR]: 	WITP{enabled,ver=2.0,path=plugins/WITP-2.0.jar}
[10:08:13] [Server thread/ERROR]: Exception details below: 
java.lang.NullPointerException: null
	at dev.efnilite.witp.player.ParkourUser.leaderboard(ParkourUser.java:280) ~[?:?]
	at dev.efnilite.witp.player.ParkourPlayer.lambda$menu$16(ParkourPlayer.java:390) ~[?:?]
	at dev.efnilite.witp.util.inventory.InventoryBuilder$ClickHandler.onClick(InventoryBuilder.java:168) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor368.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2643) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1218) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1211) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1187) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1027) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"708cdc3"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/f2f9921648885e2e0b5f4d3401737bf2c9ca5832, thanks for reporting
