### ISSUE TITLE
[Bug] Options Menu Leaderboards item out of order

### ISSUE THREAD

**Issue by slooshied** [Efnilite/Walk-in-the-Park#2]
**Describe the bug**
The leaderboards item is out of order in Options GUI.

**To Reproduce**
1. Go to 'options' while in WITP

- See photo for example

**Screenshots**
![image](https://user-images.githubusercontent.com/70556905/103594693-0b493800-4ebf-11eb-8a7c-0d175312f98f.png)

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.
`[18:56:52 WARN]: [WITP] Task #141691 for WITP v1.6a generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between witp and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.2.jar:git-Paper-189]
        at dev.efnilite.witp.generator.ParkourGenerator$1.run(ParkourGenerator.java:119) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-189]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-189]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]`

**Versions**
- Plugin version 1.6a
- Spigot/Paper version 1.16.2

**Comment by Efnilite** [comment]
Uh the leaderboard item is meant to be at the bottom since it's not an option - I'll add an option in the config so you can change where it is. Also, the error is completely unrelated to the problem but I'll look into the error as well, thanks :)
