### ISSUE TITLE
IllegalArgumentException: Cannot measure distance between witp and spawn

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#27]
Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/01146d59ea97780ff41f83805aeba1988d36de16

```
[23:13:06] [Server thread/ERROR]: [WITP] Task #263171 for WITP v2.0 generated an exception
[23:13:06] [Server thread/ERROR]: [WITP] Suspected Plugins: 
[23:13:06] [Server thread/ERROR]: [WITP] 	WITP{enabled,ver=2.0,path=plugins/WITP-2.1.jar}
[23:13:06] [Server thread/ERROR]: [WITP] Exception details below: 
java.lang.IllegalArgumentException: Cannot measure distance between witp and spawn
	at org.bukkit.Location.distanceSquared(Location.java:510) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at org.bukkit.Location.distance(Location.java:493) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at dev.efnilite.witp.player.ParkourSpectator.checkDistance(ParkourSpectator.java:58) ~[?:?]
	at dev.efnilite.witp.player.ParkourPlayer.updateSpectators(ParkourPlayer.java:130) ~[?:?]
	at dev.efnilite.witp.generator.DefaultGenerator$1.run(DefaultGenerator.java:124) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1386) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-"f295cbb"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Efnilite** [comment]
Does this still occur in the latest commit?

**Comment by mibby** [comment]
This might have been a byproduct of joining parkour multiple times and someone breaking when trying to leave while spectating. Since multiple joining is fixed / not possible anymore, I assume this is not possible anymore as well.
