### ISSUE TITLE
World save error

### ISSUE THREAD

**Issue by eloo95** [Efnilite/Walk-in-the-Park#42]
The error when saving the witp world is still there. Is it not possible to cancel the save with the event "WorldSaveEvent"?

`[19:00:03] [Server thread/ERROR]: Could not save data net.minecraft.server.v1_16_R3.PersistentRaid@7c70334b
java.io.FileNotFoundException: ./witp/data/raids.dat (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_275]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_275]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_275]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_275]
	at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:81) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PersistentBase.a(SourceFile:51) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldPersistentData.a(WorldPersistentData.java:194) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.aj(WorldServer.java:1024) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.saveData(WorldServer.java:1018) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.WorldServer.saveIncrementally(WorldServer.java:966) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1239) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Comment by Efnilite** [comment]
> Is it not possible to cancel the save with the event "WorldSaveEvent"?
This event can't be cancelled.
What's causing your world to be saved? Are you stopping the server? When stopping, it should unload the world, making it not save.. very strange.

**Comment by Efnilite** [comment]
I think this has been fixed since 2.4d, if it hasn't been please tell me.
Thanks for reporting! <3
