### ISSUE TITLE
An internal error occured when joining parkour

### ISSUE THREAD

**Issue by Neocky** [Efnilite/Walk-in-the-Park#43]
**Describe the bug**
When attempting to join the parkour with `/witp join` the plugin breaks and i get a `An internal error occured while performing this command` message. I get teleported to the start platform but only see a emeraldblock and can't do the parkour. I can't use any other /witp command. Only the `/witp leave` command works which will bring me back to spawn.

**To Reproduce**
1. Attempting to join the parkour with /witp join
2. See: `An internal error occured while performing this command`
3. See error in log

**Errors**
```
[19:21:22 INFO]: Neocky issued server command: /witp join
[19:21:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'witp' in plugin WITP v2.3c
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at dev.efnilite.witp.util.config.Configuration.getItemData(Configuration.java:178) ~[?:?]
        at dev.efnilite.witp.util.config.Configuration.getFromItemData(Configuration.java:166) ~[?:?]
        at dev.efnilite.witp.generator.subarea.SubareaDivider.createIsland(SubareaDivider.java:301) ~[?:?]
        at dev.efnilite.witp.generator.subarea.SubareaDivider.generate(SubareaDivider.java:152) ~[?:?]
        at dev.efnilite.witp.player.ParkourPlayer.<init>(ParkourPlayer.java:89) ~[?:?]
        at dev.efnilite.witp.player.ParkourPlayer.register(ParkourPlayer.java:602) ~[?:?]
        at dev.efnilite.witp.command.MainCommand.execute(MainCommand.java:102) ~[?:?]
        at dev.efnilite.witp.util.wrapper.BukkitCommand.onCommand(BukkitCommand.java:49) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-629]
        ... 19 more
[19:21:28 INFO]: Neocky issued server command: /witp menu
[19:21:31 INFO]: Neocky issued server command: /witp leave
[19:21:31 ERROR]: [WITP] Generator of player is null while trying to unregister!
```
**Versions**
- 2.3c (latest)
- Paper-629 & before Paper-584 with the same problem

**Comment by Efnilite** [comment]
It seems like the `lore` of the `general.menu` item in the language you're currently using doesn't exist. I've fixed this issue in the build added to this comment.

[target.zip](https://github.com/Efnilite/Walk-in-the-Park/files/6397486/target.zip)
