### ISSUE TITLE
MysqlDataTruncation: Data truncation: Data too long for column 'hsdiff' at row 1

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#47]
**Describe the bug**
MySQL error updating table data when joining and leaving WITP course.

**To Reproduce**
1. Join course.
2. Get a score.
3. Fall off.
4. Leave WITP.
5. Error.

**Errors**
```
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'hsdiff' at row 1
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at dev.efnilite.witp.util.sql.Database.query(Database.java:44)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at dev.efnilite.witp.util.sql.UpdateStatement.query(UpdateStatement.java:47)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at dev.efnilite.witp.util.sql.UpdertStatement.query(UpdertStatement.java:56)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at dev.efnilite.witp.player.ParkourPlayer.lambda$save$28(ParkourPlayer.java:539)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[04:16:36] [Craft Scheduler Thread - 198 - WITP/ERROR]: [WITP] Error while trying to update MySQL database!
[04:16:36] [Craft Scheduler Thread - 198 - WITP/ERROR]: [WITP] Query: UPDATE `players` SET uuid = '24b95709-012c-4dee-a324-c37ff1a4e56c', name = 'rtcabooservb', highscore = 50, hstime = '41.2s', lang = 'en', hsdiff = 'null' WHERE `uuid` = '24b95709-012c-4dee-a324-c37ff1a4e56c';
```

**Versions**
- WITP v2.4c
- Paper dev 112 (1.17.1)

**Comment by Efnilite** [comment]
This error was fixed in commit c73470eb11b5e1d54420b88819c3cac808088fdc, despite it being a different situation, I'll look into why it was null to begin with though.
Thanks for reporting!

**Comment by mibby** [comment]
Thanks! Do you have any dev builds for the fix or should I just compile it until the next version release?

**Comment by Efnilite** [comment]
I don't currently have any dev builds for it, if it's not a big pain you can compile it yourself and it should work fine
