### ISSUE TITLE
Use default preset if style is no longer existing.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#49]
WITP joins break if you have a preset that no longer exists in the config set as your default. Should fallback to first listed as a default if not existing to prevent breakage since you can't open the GUI to change it back or generate blocks.

```
[21:02:46] [Server thread/ERROR]: [WITP] Style selected (amethyst) doesn't exist in config.yml!
[21:02:46] [Server thread/WARN]: [ServerSigns] Error while executing task PlayerTask{data='parkour join'} de.czymm.serversigns.taskmanager.tasks.PlayerActionTask@33cf2d9e
org.bukkit.command.CommandException: Unhandled exception executing command 'parkour' in plugin WITP v2.4c
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:652) ~[patched_1.17.1.jar:git-Purpur-1285]
	at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.performCommand(PlayerActionTask.java:39) ~[?:?]
	at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.lambda$runPlayerTask$0(PlayerActionTask.java:68) ~[?:?]
	at de.czymm.serversigns.ServerSignsPlugin.runOnMainThread(ServerSignsPlugin.java:269) ~[?:?]
	at de.czymm.serversigns.taskmanager.tasks.PlayerActionTask.runPlayerTask(PlayerActionTask.java:68) ~[?:?]
	at de.czymm.serversigns.taskmanager.tasks.PlayerTask.runTask(PlayerTask.java:51) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTaskImpl(TaskManagerTaskExecutor.java:62) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:55) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManagerTaskExecutor.runTask(TaskManagerTaskExecutor.java:31) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManager.addTask(TaskManager.java:109) ~[?:?]
	at de.czymm.serversigns.taskmanager.TaskManager.addAllTasks(TaskManager.java:121) ~[?:?]
	at de.czymm.serversigns.signs.ServerSignExecutor.createCommandTasks(ServerSignExecutor.java:229) ~[?:?]
	at de.czymm.serversigns.signs.ServerSignExecutor.executeSignFull(ServerSignExecutor.java:104) ~[?:?]
	at de.czymm.serversigns.listeners.PlayerListener.playerInteractCheck(PlayerListener.java:106) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor695.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1285]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1285]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:543) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1853) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1285]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1285]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.possibleStyle" is null
	at dev.efnilite.witp.player.ParkourPlayer.randomMaterial(ParkourPlayer.java:193) ~[?:?]
	at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:431) ~[?:?]
	at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:644) ~[?:?]
	at dev.efnilite.witp.player.ParkourPlayer.setDefaults(ParkourPlayer.java:116) ~[?:?]
	at dev.efnilite.witp.player.ParkourPlayer.register(ParkourPlayer.java:753) ~[?:?]
	at dev.efnilite.witp.player.ParkourPlayer.register(ParkourPlayer.java:661) ~[?:?]
	at dev.efnilite.witp.command.MainCommand.execute(MainCommand.java:109) ~[?:?]
	at dev.efnilite.witp.util.wrapper.BukkitCommand.onCommand(BukkitCommand.java:49) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1285]
	... 40 more
```

**Comment by Efnilite** [comment]
Fixed in the next upcoming commit, thanks for reporting!
