### ISSUE TITLE
Plugin is disabled upon installation

### ISSUE THREAD

**Issue by slooshied** [Efnilite/Walk-in-the-Park#5]
**Describe the bug**

Plugin is disabled upon installation

**To Reproduce**
1. Install plugin
2. Start server

**Screenshots**

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.

```
[21:26:38 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'witp' in plugin WITP v1.9 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-396]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Versions**
- Plugin version 1.9 (latest)
- Spigot/Paper version 1.16.4 (Build #396)

**Comment by Efnilite** [comment]
When a plugin is disabled, it says so at the very beginning of when your server starts, so it'd be great if you could share your start log. (further information required)

**Comment by slooshied** [comment]
```
[16:36:08 INFO]: [WITP] Enabling WITP v1.9
[16:36:08 INFO]: [PlaceholderAPI] Successfully registered expansion: witp
[16:36:08 ERROR]: Error occurred while enabling WITP v1.9 (Is it up to date?)
java.lang.NullPointerException: null
        at dev.efnilite.witp.util.Util.color(Util.java:378) ~[?:?]
        at dev.efnilite.witp.generator.ParkourGenerator$Configurable.init(ParkourGenerator.java:685) ~[?:?]
        at dev.efnilite.witp.WITP.onEnable(WITP.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-396]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        
```
        Apologies.

**Comment by slooshied** [comment]
`[19:07:30 ERROR]: Error occurred while enabling WITP v1.9a (Is it up to date?)
java.lang.NullPointerException: null
        at dev.efnilite.witp.util.Util.color(Util.java:362) ~[?:?]
        at dev.efnilite.witp.generator.ParkourGenerator$Configurable.init(ParkourGenerator.java:685) ~[?:?]
        at dev.efnilite.witp.WITP.onEnable(WITP.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-396]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
        
        I will say this is also occuring on update 1.9a - here is the startup disable message
        
        
        Error when someone does /witp:
        
        `[19:56:48 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'witp' in plugin WITP v1.9a - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1928) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.chat(CraftPlayer.java:487) ~[patched_1.16.4.jar:git-Paper-396]
        at it.emmerrei.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:1377) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:1254) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:990) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:990) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:990) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:990) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:990) ~[?:?]
        at it.emmerrei.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:515) ~[?:?]
        at it.emmerrei.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:282) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor322.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-396]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-396]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2013) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-396]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-396]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Efnilite** [comment]
Oh, because you updated you need to delete your config files so it can regenerate with the new and updated values (I still need to figure out how to make it not delete to update, sorry)
