### ISSUE TITLE
IllegalStateException: The instance wasn't set!

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#50]
WITP v2.4e
Multiverse-Core dev 857 (https://ci.onarandombox.com/job/Multiverse-Core/)
VoidGen 2.0

```
[23:41:38] [Server thread/ERROR]: Error occurred while enabling WITP v2.4e (Is it up to date?)
java.lang.IllegalStateException: The instance wasn't set!
	at com.onarandombox.MultiverseCore.MultiverseCoreConfiguration.getInstance(MultiverseCoreConfiguration.java:40) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:497) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:288) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:228) ~[?:?]
	at dev.efnilite.witp.hook.MultiverseHook.createWorld(MultiverseHook.java:31) ~[?:?]
	at dev.efnilite.witp.generator.subarea.SubareaDivider.createWorld(SubareaDivider.java:253) ~[?:?]
	at dev.efnilite.witp.generator.subarea.SubareaDivider.<init>(SubareaDivider.java:94) ~[?:?]
	at dev.efnilite.witp.WITP.onEnable(WITP.java:106) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Purpur-1300]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1300]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1300]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:41:38] [Server thread/INFO]: [WITP] Disabling WITP v2.4e
```

**Comment by Efnilite** [comment]
This has already been fixed in the latest commit

**Comment by mibby** [comment]
Not pushed to the repo yet? As I tried the official v2.4e released build & compiling latest source.

**Comment by Efnilite** [comment]
Not yet, currently working on a massive update, so when I finish that I'll release (probably tomorrow or so)

**Comment by mibby** [comment]
Great, thanks. Hopefully all goes well! I've just downgraded to 2.4c in the meantime.
