### ISSUE TITLE
Time doesn't stay set when you fall

### ISSUE THREAD

**Issue by slooshied** [Efnilite/Walk-in-the-Park#6]
**Describe the bug**

When you fail to make a jump with the time set to a certain value, it will automatically re-set the time to noon.

**To Reproduce**
1. Go to "Options."
2. Click on 'Time preference'
3. Fail to make a jump

**Screenshots**

https://user-images.githubusercontent.com/70556905/104404998-95c61300-5521-11eb-93d4-750c40586f9c.mp4

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.

I don't think this has anything to do with it but it is displaying

[21:59:47 ERROR]: Could not save data net.minecraft.server.v1_16_R3.PersistentRaid@1d6f46ec
java.io.FileNotFoundException: .\witp\data\raids.dat (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method) ~[?:?]
        at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
        at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:81) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.PersistentBase.a(SourceFile:51) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.WorldPersistentData.a(WorldPersistentData.java:194) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.WorldServer.aj(WorldServer.java:1024) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.WorldServer.saveData(WorldServer.java:1018) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.WorldServer.saveIncrementally(WorldServer.java:966) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1235) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[paper-1.16.4.jar:git-Paper-407]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[paper-1.16.4.jar:git-Paper-407]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Versions**
- Plugin version 1.9b
- Spigot/Paper version 1.16.4 Build#407

**Additional context**

**Comment by Efnilite** [comment]
This doesn't happen to me in v1.9c (latest release). Could you perhaps test it with the latest version and see if the problem still persists? (I might have accidentally fixed it in the latest release)

**Comment by slooshied** [comment]
Unfortunately, It seems that the problem is still happening. 

https://user-images.githubusercontent.com/70556905/104558314-3abb1b80-5608-11eb-999e-4bde2c88b45b.mp4

**Comment by Efnilite** [comment]
I have no idea why this is happening - it's probably because some other plugin might be interfering. I could add a feature that makes it so you can disable players changing time if you want.

**Comment by Efnilite** [comment]
I really don't have a clue to how it's happening - the player time only gets changed when leaving and joining. In the latest commit (and latest release) I've added a way to disable time changing, which is the best I can do for now.. sorry ;-;

**Comment by slooshied** [comment]
No worries! Sorry I've been busy with some academic things. Happy to hear there's a semi-solution. Thanks for the attempt!
