### ISSUE TITLE
I'm getting an error in v2.9

### ISSUE THREAD

**Issue by Strahilchu** [Efnilite/Walk-in-the-Park#68]
**Describe the bug**
Console error and block delay when generating

[14:49:51 WARN]: [WITP] Task #76 for WITP v2.9 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.isLegacy()" because "material" is null
        at org.bukkit.craftbukkit.v1_18_R1.util.CraftLegacy.modern_ordinal(CraftLegacy.java:35) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at dev.efnilite.witp.generator.DefaultGenerator.selectBlocks(DefaultGenerator.java:165) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:440) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:717) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.tick(DefaultGenerator.java:300) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator$1.run(DefaultGenerator.java:228) ~[WITP-2.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1549) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:49:55 WARN]: [WITP] Task #76 for WITP v2.9 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.isLegacy()" because "material" is null
        at org.bukkit.craftbukkit.v1_18_R1.util.CraftLegacy.modern_ordinal(CraftLegacy.java:35) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at dev.efnilite.witp.generator.DefaultGenerator.selectBlocks(DefaultGenerator.java:165) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:440) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.generate(DefaultGenerator.java:717) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator.tick(DefaultGenerator.java:300) ~[WITP-2.9.jar:?]
        at dev.efnilite.witp.generator.DefaultGenerator$1.run(DefaultGenerator.java:228) ~[WITP-2.9.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1549) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Versions**
- Plugin version: 2.9
- Spigot/Paper version. 1.18.1 latest release as of January 16, 2022

**Comment by Strahilchu** [comment]
Happens in Paper and Pufferfish, server.jar made no difference. Config is default aside from scoreboard text changes etc

Plugins (10): AdvancedPortals, CMI, CMILib, ImageMaps, LuckPerms, VoidGen, Vulcan, WITP, WorldEdit, WorldGuard

**Comment by Strahilchu** [comment]
Error does not happen when using WITP-2.8e.jar

**Comment by Efnilite** [comment]
Fixed in 3c5b0c922543fccd0195f74b7222d9c32c0947b8, thanks for reporting! I will update the 2.9 jar so download it again and it will work :)

**Comment by Efnilite** [comment]
The jar has been updated.
