### ISSUE TITLE
IllegalArgumentException: bound must be greater than origin

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#82]
```
[00:27:21] [Server thread/WARN]: [WITP] Task #20219 for WITP v3.4.3 generated an exception
java.lang.IllegalArgumentException: bound must be greater than origin
	at jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232) ~[?:?]
	at java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679) ~[?:?]
	at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:458) ~[?:?]
	at dev.efnilite.ip.generator.DefaultGenerator.selectNext(DefaultGenerator.java:228) ~[WITP-3.4.3.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator.selectBlocks(DefaultGenerator.java:194) ~[WITP-3.4.3.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator.generate(DefaultGenerator.java:503) ~[WITP-3.4.3.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator.generate(DefaultGenerator.java:591) ~[WITP-3.4.3.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator.tick(DefaultGenerator.java:345) ~[WITP-3.4.3.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator$1.run(DefaultGenerator.java:279) ~[WITP-3.4.3.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1685]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1685]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1685]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1685]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1685]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1685]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1685]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Efnilite** [comment]
Fixed in v3.4.4
