### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by Folas1337** [Efnilite/Walk-in-the-Park#83]
**Describe the bug**
I'm getting the following error in the console if I basically use any "/witp" command:
(see below for error message)

**To Reproduce**
I'm not sure why it suddenly started happening and I tried restarting the server already.

**Errors**
``  [Wed 17:39:08 INFO  Server/PlayerConnection] Folas1337 issued server command: /witp join
- [Wed 17:39:08 ERROR Server/PlayerConnection] null
org.bukkit.command.CommandException: Unhandled exception executing command 'witp' in plugin WITP v3.4.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335)
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328)
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: dev/efnilite/ip/player/data/InventoryData
    at IP.jar//dev.efnilite.ip.player.data.PreviousData.<init>(PreviousData.java:56)
    at IP.jar//dev.efnilite.ip.player.ParkourUser.<init>(ParkourUser.java:71)
    at IP.jar//dev.efnilite.ip.player.ParkourPlayer.<init>(ParkourPlayer.java:7``

**Versions**
 Running WITP version 3.4.2, vililib 1.0.8 and paper 1.19 build 39

**Comment by Folas1337** [comment]
You do realize how that means it wasn't the version's fault or there is code that creates inventory data that isn't valid?
I suggest looking into this, it could lead to more people reporting this and also just thinking that the plugin downright broke.

Not gonna tell you what to do, just a suggestion for a better quality plugin (that I enjoy a lot 😄)

**Comment by Efnilite** [comment]
> You do realize how that means it wasn't the version's fault or there is code that creates inventory data that isn't valid? I suggest looking into this, it could lead to more people reporting this and also just thinking that the plugin downright broke.
> 
> Not gonna tell you what to do, just a suggestion for a better quality plugin (that I enjoy a lot 😄)

The error which occured is something which is only possible because of errors on load/deload, which doesn't get caused by file reading. I'll check to see if your data still gives an error in v3.4.3 anyway.

**Comment by Efnilite** [comment]
I tried all the inventory files, seems that it was just a one-off thing.
