### ISSUE TITLE
critical error!  /parkour join

### ISSUE THREAD

**Issue by WieszczY85** [Efnilite/Walk-in-the-Park#85]
Nothing happens after entering the / parkour join command and I get the following error in the console

```
[14:25:49] [Server thread/INFO]: WieszczY issued server command: /parkour join
[14:25:50] [Server thread/ERROR]: [WITP] ##
[14:25:50] [Server thread/ERROR]: [WITP] ## WITP has encountered a critical error!
[14:25:50] [Server thread/ERROR]: [WITP] ## Error while reading SQL data of player WieszczY
[14:25:50] [Server thread/ERROR]: [WITP] ##
[14:25:50] [Server thread/ERROR]: [WITP] ## Stack trace:
[14:25:50] [Server thread/ERROR]: [WITP] ## java.lang.NullPointerException: Cannot invoke "String.trim()" because "in" is null
[14:25:50] [Server thread/ERROR]: [WITP] ##	java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
[14:25:50] [Server thread/ERROR]: [WITP] ##	java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[14:25:50] [Server thread/ERROR]: [WITP] ##	java.base/java.lang.Double.parseDouble(Double.java:651)
[14:25:50] [Server thread/ERROR]: [WITP] ##	IP.jar//dev.efnilite.ip.player.ParkourPlayer.register0(ParkourPlayer.java:406)
[14:25:50] [Server thread/ERROR]: [WITP] ##	IP.jar//dev.efnilite.ip.player.ParkourUser.register(ParkourUser.java:132)
[14:25:50] [Server thread/ERROR]: [WITP] ##	IP.jar//dev.efnilite.ip.player.ParkourUser.joinDefault(ParkourUser.java:98)
[14:25:50] [Server thread/ERROR]: [WITP] ##	IP.jar//dev.efnilite.ip.ParkourCommand.execute(ParkourCommand.java:154)
[14:25:50] [Server thread/ERROR]: [WITP] ##	vilib.jar//dev.efnilite.vilib.command.ViCommand.onCommand(ViCommand.java:149)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2376)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2289)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.chat(CraftPlayer.java:676)
[14:25:50] [Server thread/ERROR]: [WITP] ##	CommandNPC Reloaded v0.96.jar//me.messageofdeath.commandnpc.Listeners.NPCListener.onClick(NPCListener.java:154)
[14:25:50] [Server thread/ERROR]: [WITP] ##	CommandNPC Reloaded v0.96.jar//me.messageofdeath.commandnpc.Listeners.NPCListener.onRight(NPCListener.java:58)
[14:25:50] [Server thread/ERROR]: [WITP] ##	com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor710.execute(Unknown Source)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[14:25:50] [Server thread/ERROR]: [WITP] ##	co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
[14:25:50] [Server thread/ERROR]: [WITP] ##	Citizens.jar//net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:493)
[14:25:50] [Server thread/ERROR]: [WITP] ##	com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor661.execute(Unknown Source)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[14:25:50] [Server thread/ERROR]: [WITP] ##	co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:25:50] [Server thread/ERROR]: [WITP] ##	org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.network.PlayerConnection$5.performInteraction(PlayerConnection.java:2662)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2712)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2654)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.TickTask.run(TickTask.java:18)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1358)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1335)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[14:25:50] [Server thread/ERROR]: [WITP] ##	net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[14:25:50] [Server thread/ERROR]: [WITP] ##	java.base/java.lang.Thread.run(Thread.java:833)
[14:25:50] [Server thread/ERROR]: [WITP] ##
[14:25:50] [Server thread/ERROR]: [WITP] ## This is probably not your fault.
[14:25:50] [Server thread/ERROR]: [WITP] ## Contact the developer to fix it.
[14:25:50] [Server thread/ERROR]: [WITP] ## Be sure to send the entire error while reporting.
[14:25:50] [Server thread/ERROR]: [WITP] ##
[14:25:50] [Server thread/ERROR]: [WITP] ## Version information:
[14:25:50] [Server thread/ERROR]: [WITP] ##	Plugin Version: 3.5.3
[14:25:50] [Server thread/ERROR]: [WITP] ##	vilib Version: 1.0.10
[14:25:50] [Server thread/ERROR]: [WITP] ##	Minecraft: V1.19
[14:25:50] [Server thread/ERROR]: [WITP] ##
[14:25:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'parkour' in plugin WITP v3.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2289) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.chat(CraftPlayer.java:676) ~[paper-1.19.jar:git-Paper-61]
	at me.messageofdeath.commandnpc.Listeners.NPCListener.onClick(NPCListener.java:154) ~[CommandNPC Reloaded v0.96.jar:?]
	at me.messageofdeath.commandnpc.Listeners.NPCListener.onRight(NPCListener.java:58) ~[CommandNPC Reloaded v0.96.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor710.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-61]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:493) ~[Citizens.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor661.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-61]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2662) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2712) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2654) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-61]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.player.useScoreDifficulty" is null
	at dev.efnilite.ip.generator.base.DefaultGeneratorChances.calculateDistance(DefaultGeneratorChances.java:188) ~[IP.jar:?]
	at dev.efnilite.ip.generator.base.DefaultGeneratorChances.calculateChances(DefaultGeneratorChances.java:83) ~[IP.jar:?]
	at dev.efnilite.ip.generator.base.DefaultGeneratorChances.<init>(DefaultGeneratorChances.java:61) ~[IP.jar:?]
	at dev.efnilite.ip.generator.base.DefaultGeneratorBase.<init>(DefaultGeneratorBase.java:40) ~[IP.jar:?]
	at dev.efnilite.ip.generator.DefaultGenerator.<init>(DefaultGenerator.java:106) ~[IP.jar:?]
	at dev.efnilite.ip.IP.getVersionGenerator(IP.java:214) ~[IP.jar:?]
	at dev.efnilite.ip.player.ParkourPlayer.getGenerator(ParkourPlayer.java:476) ~[IP.jar:?]
	at dev.efnilite.ip.world.WorldDivider.createIsland(WorldDivider.java:217) ~[IP.jar:?]
	at dev.efnilite.ip.world.WorldDivider.generate(WorldDivider.java:131) ~[IP.jar:?]
	at dev.efnilite.ip.world.WorldDivider.generate(WorldDivider.java:98) ~[IP.jar:?]
	at dev.efnilite.ip.player.ParkourUser.joinDefault(ParkourUser.java:99) ~[IP.jar:?]
	at dev.efnilite.ip.ParkourCommand.execute(ParkourCommand.java:154) ~[IP.jar:?]
	at dev.efnilite.vilib.command.ViCommand.onCommand(ViCommand.java:149) ~[vilib.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 39 more
[14:25:50] [Server thread/INFO]: [com.fastasyncworldedit.bukkit.listener.ChunkListener] [FAWE Tick Limiter] Detected and cancelled physics lag source at Location{world=CraftWorld{name=witp},x=11.0,y=135.0,z=11.0,pitch=0.0,yaw=0.0}


```

**Comment by Efnilite** [comment]
Fixed in [v3.5.4](https://github.com/Efnilite/Walk-in-the-Park/releases/tag/v3.5.4), thanks for reporting!
